Develop
Kartinkartin/givenchy pull request #2
Opened 2022-04-08 19:04 UTC by Kartinkartin

2022-04-09 15:16 UTC, vgschevchenko requested changes
Хорошая и достойная работа, мне было приятно ее проверять. 
Работа оставила приятное впечатление. 
Исправьте все ошибки, чтобы вы смогли добавить работу в свое портфолио. 


## Что понравилось:

* Отличный и самое главное плавный адаптив. Элементы тянутся, здорово!
* Валидатор `html` не ругается на ошибки. 
* Код в целом хорошо отформатирован.
* Хорошо реализовали nested файловую структуру для проекта.
* Используются псевдоклассы/псевдоэлементы для упрощения верстки. 

	
## Критерии

1. Соответствие макету
    - [x] <!--10.0--> 1.1 Все элементы из макета сверстаны
    - [x] <!--4.0--> 1.2 Шрифты, размер, цвет и начертания текста соответствуют макету
    - [x] <!--4.0--> 1.3 Ширина элементов и отступы отличаются от макета не более, чем на `30px` на десктопной версии и на `10px` на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета
	**Комментарий: Нужно указать корректную позицию фона согласно макету. https://skr.sh/sDNrKPo99k8**
	**Комментарий: Расположение элемента в блоке header https://skr.sh/sDNnwgRVXqL**
	**Комментарий: 	Фон нужно прижать к нижней границе блока https://skr.sh/sDNHiXZva7k**
	**Комментарий: Необходимо сравнить стилизацию текста с макетом и если необходимо скоректировать данный момент. https://skr.sh/sDNYEsp6FoA**
	**Комментарий: Высота блока указана некорректно https://skr.sh/sDNQtk3WokV**
	**Комментарий: Укажите корректные отступы между элементами, внутри блока и размеры самих элементов. Сравните отображение текста с макетом. https://skr.sh/sDNOcpWuoHy**
	**Комментарий: Расположение блока или элемента на странице. https://skr.sh/sDNu2Tnhdc8**
	**Комментарий: Отступ между блоками указан некорректно https://skr.sh/sDNZAjwqrcZ**
	**Комментарий: Отступ между блоками указан некорректно https://skr.sh/sDN4rMLds4g**
	**Комментарий: Расположение фона на мобильных https://skr.sh/sDNQAZg8iZK**
	**Комментарий: Размер кнопки на мобильных https://skr.sh/sDNQrFITDKK**
    - [x] <!--2.0--> 1.4 Все блоки соответствуют макету в последних версиях Firefox, Google Chrome или Yandex Browser
2. Адаптив
    - [x] <!--4.0--> 2.1 Отсутствует горизонтальный скролл на всех размерах экрана 320px и более
    - [x] <!--1.0--> 2.2 Установленная максимальная ширина контента соответствует макету
    - [x] <!--4.0--> 2.3 Верстка не ломается между брейкпоинтами
    - [x] <!--1.0--> 2.4 Брейкпоинты сгруппированы. Если два брейкпоинта имеют небольшую пиксельную разницу в медиа-правиле они объединены в один
    - [x] <!--4.0--> 2.5 Текст не выпадает из блоков на всех размерах экрана 320px и более 
    - [x] <!--3.0--> 2.6 Изображения не искажаются и выглядят как в макете на всех размерах экрана
    - [x] <!--1.0--> 2.7 Одинаковые свойства в разных медиа-правилах не дублируются
3. Верстка
    - [x] <!--4.0--> 3.1 Нет ошибок валидации [https://validator.w3.org/nu/](https://validator.w3.org/nu/) (Erorrs)
    - [ ] <!--3.0--> 3.2 Используются `<main>`, `<section>`, `<header>`, `<footer>`, `<ul>`, `<nav>`, `<h1-h6>` и `<p>` там, где это необходимо
    - [x] <!--2.0--> 3.3 Не используются элементы `<b>`, `<br>`, `<i>`
    - [x] <!--1.0--> 3.4 Отсутствуют лишние `div` обертки 
    - [x] <!--3.0--> 3.5 Контентные картинки вставлены через `<img>`, и в них присутствует `alt` с описанием, которое соответствует языку страницы
    - [x] <!--2.0--> 3.6 На странице есть заголовок первого уровня
    - [x] <!--2.0--> 3.7 Заголовки соответствуют иерархии страницы
    - [x] <!--1.0--> 3.8 Корректно задан `viewport`, прописаны `title` и `lang`.
4.  CSS
    - [x] <!--2.0--> 4.1 Не используется `!important`
    - [x] <!--2.0--> 4.2 Абсолютное позиционирование не используется без непосредственной необходимости
    - [x] <!--4.0--> 4.3 Использование `height` и `max-height` не приводит к выпадению текста или блоков при переполнении
    - [ ] <!--2.0--> 4.4 Любой интерактивный элемент имеет состояние наведения, состояние наведения берется из макета или используется прозрачность
    - [x] <!--1.0--> 4.5 Для каждого шрифта указаны альтернативные варианты из системных шрифтов и тип шрифта
5. Применение БЭМ
    - [ ] <!--4.0--> 5.1 Нет нарушения методологии БЭМ: нет элементов без родительского блока, нет элементов элементов, модификаторы не используются без указания того, что они модифицируют
    - [x] <!--2.0--> 5.2 Не используются селекторы по тегу
    - [x] <!--3.0--> 5.3 Для одинаковых блоков в макете переиспользуется стили одного БЭМ-блока
    - [x] <!--1.0--> 5.4 Числа в названиях классов не используются, за исключением классов для элементов, указанных в руководстве по стилю (Style Guide)
    - [ ] <!--1.0--> 5.5 Модификатор не отражает позицию элемента в разметке (`paragraph_first`)
    - [x] <!--1.0--> 5.6 Модификаторы не содержат дубли стилей модифицируемого элемента или блока, только изменяющиеся свойства
    - [ ] <!--2.0--> 5.7 Файловая структура построена по БЭМ Nested или БЭМ Flat
	**Комментарий: Вам нужно определиться, поскольку сейчас у вас смешанный тип Файловой структуры**
	- [x] <!--10.0--> 6. Функциональность на JS работает корректно (слайдеры, бургерное меню или другие требования согласно заданию на проект)
7. Структура проекта и оформление кода
    - [ ] <!--2.0--> 7.1 Соблюдена единообразная файловая структура проекта, например, изображения в папке images, шрифты в папке fonts, стили в папке blocks, скрипты в папке scripts, а не разбросаны в разных папках и не хранятся в корне проекта
    - [ ] <!--1.0--> 7.2 Код в проекте отформатирован единообразно
    - [x] <!--1.0--> 7.3 Нет нарушений иерархии отступов в разметке, стилях и файлах скриптов
8. Использование SCSS
	- [x] <!--2.0--> 8.1 Файлы стилей имеют расширение SCSS, подключаемый к странице CSS файл получен генерацией из SCSS файлов 
	- [x] <!--2.0--> 8.2 Повторяющеся значения вынесены в переменные, например, используемые цвета, шрифты, размеры экрана для медиазапросов
	- [x] <!--1.0--> 8.3 Корректно используются миксины, миксины не состоят из одного CSS свойства

## Доп. комментарии:

## Количество баллов: 81

##

2022-04-09 15:16 UTC, vgschevchenko commented on blocks/header/header.scss
> +    background-image: url(../images/image1.jpg);
Нужно указать корректную позицию фона согласно макету. https://skr.sh/sDNrKPo99k8

2022-04-09 15:16 UTC, vgschevchenko commented on blocks/title/_location/title_location_header.css
> +.title_location_header {
Расположение элемента в блоке header https://skr.sh/sDNnwgRVXqL

2022-04-09 15:16 UTC, vgschevchenko commented on blocks/header/header.scss
> +    background-image: url(../images/image1.jpg);
Фон нужно прижать к нижней границе блока https://skr.sh/sDNHiXZva7k

2022-04-09 15:16 UTC, vgschevchenko commented on blocks/title/title.scss
> +.title {
Необходимо сравнить стилизацию текста с макетом и если необходимо скоректировать данный момент. https://skr.sh/sDNYEsp6FoA

2022-04-09 15:16 UTC, vgschevchenko commented on blocks/header/header.scss
> +.header {
Высота блока указана некорректно https://skr.sh/sDNQtk3WokV

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +    <section class="about" id="about">
Укажите корректные отступы между элементами, внутри блока и размеры самих элементов. 
Сравните отображение текста с макетом. https://skr.sh/sDNOcpWuoHy

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +        <p class="content-text about__second-description">Matthew M. Williams reveals his vision with help from an&nbsp;all-star lineup of&nbsp;likeminded artists. The Creative Director called on&nbs
Расположение блока или элемента на странице. https://skr.sh/sDNu2Tnhdc8

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +    <footer class="footer">
Отступ между блоками указан некорректно https://skr.sh/sDNZAjwqrcZ

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +    </section>
Отступ между блоками указан некорректно https://skr.sh/sDN4rMLds4g

2022-04-09 15:16 UTC, vgschevchenko commented on blocks/header/header.scss
> +}
Расположение фона на мобильных https://skr.sh/sDNQAZg8iZK

2022-04-09 15:16 UTC, vgschevchenko commented on blocks/button/button.css
> +  color: #fff;
Размер кнопки на мобильных https://skr.sh/sDNQrFITDKK

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +<body class="page">
Пишу общий комментарий. 
В целом много несоотвесвтий с макетом, что касется отступов и расположения элементов. 
Сравните еще раз с каждым из маектов.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +            <button class="menu__button"></button>
Необходимо указать тип для ВСЕХ кнопок в коде. 
Если это обычная кнопка, то тогда тип `button`. 
Это полезно для доступности в будущем при разработки, а также и для сео. 
По внешнему виду кнопки разного типа никак не различаются, но у каждой такой кнопки свои функции. https://webref.ru/html/button/type

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +            <button class="button button_location_header" onclick="document.location.href='#subscribe-form'">Subscribe to collection&grave;s news</button>
js внутри html лучше убрать.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +            <span class="title__line">GIVENCHY</span><span class="title__line">SPRING&nbsp;SUMMER 2021</span><span class="title__line">BY&nbsp;MATTHEW&nbsp;M. WILLIAMS</span>
Элемент `span` внутри заголовка нужно убрать. 
Чтобы добиться нужного переноса текста, просто укажите корректную максимальную ширину для заголовка пока не добьетесь нужного результата.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +        <nav class="menu">
В соотвествии с БЭМ, мы не используем числительные в названиях классов.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +            <button class="button button_location_header" onclick="document.location.href='#subscribe-form'">Subscribe to collection&grave;s news</button>
В соотвествии с БЭМ, мы не используем числительные в названиях классов.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +        <img class="about__first-image" src="./images/_0016_1080X13506.jpg" alt="Модель в красном">
В соотвествии с БЭМ, мы не используем числительные в названиях классов.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +        <div class="about__first-quote-container">
В соотвествии с БЭМ, мы не используем числительные в названиях классов.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +            <cite class="about__author">Matthew M. Williams.</cite>
Для улучшения семантики перечисляемые блоки можно выделить в список `ul`. 
Обратите внимание, что у списков следует убрать стандартные стили: `margin`, `padding`, `list-style-type`

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +    <div class="popup-shield"></div>
Меню всегда должно занимать всю высоту страницы. https://skr.sh/sDNPpxeU9in

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +    <div class="popup">
Необходимо указать тип для ВСЕХ кнопок в коде. 
Если это обычная кнопка, то тогда тип `button`. 
Это полезно для доступности в будущем при разработки, а также и для сео. 
По внешнему виду кнопки разного типа никак не различаются, но у каждой такой кнопки свои функции. https://webref.ru/html/button/type

2022-04-09 15:16 UTC, vgschevchenko commented on blocks/popup/popup.scss
> +    transition: left 1.3s linear;
Очень длинная задержка анимании, для появления меню.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +        <nav class="menu">
Это не навигация, поэтому тег `nav` тут будет лишним.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +    <section class="about" id="about">
Все основные блоки, кроме `header, footer`, должны быть вложены в один общий тег `main`.
Элементу необходимо не забыть указать корректный класс.
Это делает страницу сематические верной и привлекательной для поисковых машин, смотрите ссылку ниже.
https://www.w3schools.com/html/html5_semantic_elements.asp

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +        <p class="content-text about__first-description">The Spring-Summer &grave;21 collection explores Givenchy in&nbsp;the&nbsp;form of a&nbsp;stream of consciousness for&nbsp;Williams and is a&nb
В соотвествии с БЭМ, мы не используем числительные в названиях классов.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +        <img class="about__first-image" src="./images/_0016_1080X13506.jpg" alt="Модель в красном">
В соотвествии с БЭМ, мы не используем числительные в названиях классов.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +        <div class="about__first-quote-container">
В соотвествии с БЭМ, мы не используем числительные в названиях классов.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +        <form class="subscribe-form" id="subscribe-form">
Для формы необходимо указать уникальное имя(атрибут) `name`.
Данный атрибут задает форме уникальность для ее поиска в dom дереве и  для последующей работы с введенными в нее данными и манипуляциями при помощи javaScript и т.д
https://webref.ru/html/form/name

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +                    <span class="subscribe-form__accept-text">I&nbsp;consent to&nbsp;the&nbsp;processing of&nbsp;my&nbsp;data by&nbsp;GIVENCHY in&nbsp;accordance with the&nbsp;conditions set forth in
Тут лучше всего использовать параграф - тег span не имеет семантического значения.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +                <input type="email" placeholder="Enter your email  here" class="subscribe-form__email-input" id="subscribe">
Для полей не хватает атрибута `name`,  он необходим для последующей работы с формой и введенными данными, а также задает уникальность данному полю ввода.
https://webref.ru/html/input/name

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +<script src="./index.js"></script>
* Необходимо отформатировать код в `html`: отступы не соблюдены.

2022-04-09 15:16 UTC, vgschevchenko commented on blocks/button/button.scss
> +    &_location_header {
Нужно соблюдать единную структуру. 
Если вы решили выносить модификаторы в отдельную директорию внутри блока или элемента, то стоит этого придерживаться и для других блоков или элементов. 
Сейчас у вас модификаторв выполнен внутри блока, а в других блоках вы выносили их в отедьнрую директорию.

2022-04-09 15:16 UTC, vgschevchenko commented on blocks/page/page.scss
> +.page {
• Считается хорошей практикой указывать максимальную и минимальную ширину для всей страницы, чтобы она не ломалась ниже минимальной точки и не распластывалась по всему окну.

2022-04-09 15:16 UTC, vgschevchenko commented on pages/index.scss
> +
У вас присутствуют ошибки при формировании БЭМ структуры. 
Вам нужно определиться, какой тип вы будете использовать `flat` или `nested`.
Если говорить о `nested`, то она подразумевает создания под каждого элемента своей директории и файла со стилями. 
Сейчас вы используете и тот и другой, это не очень корректный подход. 
Вам нужно определиться.

2022-04-09 15:16 UTC, vgschevchenko commented on _mixins.scss
> +
Можно лучше: Еще можно создать миксин, который будет генерировать нужные медизапросы.

2022-04-09 15:16 UTC, vgschevchenko commented on index.js
> +    popupMenu.classList.remove('popup-visible');
Название модификатора сформировано  некорректно.
Оно должно отражать состояние, а не название языка, элемента и т.д.
Модификатор необходимо сделать "сложным". 
Его название должно формироваться по одному из принципу, например "ключ-значение".
https://ru.bem.info/methodology/quick-start/#%D0%BA%D0%BB%D1%8E%D1%87-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5

2022-04-09 15:16 UTC, vgschevchenko commented on blocks/popup/popup.scss
> +    &-visible{
Название модификатора сформировано  некорректно.
Оно должно отражать состояние, а не название языка, элемента и т.д.
Модификатор необходимо сделать "сложным". 
Его название должно формироваться по одному из принципу, например "ключ-значение".
https://ru.bem.info/methodology/quick-start/#%D0%BA%D0%BB%D1%8E%D1%87-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5

2022-04-09 15:16 UTC, vgschevchenko commented on index.js
> +buttonMenu.addEventListener('click', function () {
Можно лучше: Вынести функцию открытия попапа в отдельное выражение и дать ей название, чтобы можно было потом использолвать в других местах.

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +                    <span class="subscribe-form__pseudo-item"></span>
Можно лучше: Данный элемент можно сделать при помощи псевдоэлементов css

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +                <a href="#about" class="popup__link">About</a>
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

#### Исправьте для всех ссылок или интерактивных элементов на  странице. 
https://skr.sh/sDNAiv1bqlF

2022-04-09 15:16 UTC, vgschevchenko commented on index.html
> +        <button class="button-close"></button>
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

2022-04-09 15:16 UTC, vgschevchenko commented on _variables.scss
> +
Можно лучше: Для всех файлов в том числе и директории `blocks` можно создать общую директорию `styles` и сложить их туда, чтобы они не были раскиданы по проекту.

2022-04-09 15:16 UTC, vgschevchenko commented on blocks/about/about.scss
> +            grid-row: 2;}
* Необходимо отформатировать код в `css`: отступы не соблюдены.

2022-04-11 18:46 UTC, Kartinkartin commented on blocks/popup/popup.scss
> +    transition: left 1.3s linear;
сократила до секунда длительность анимации, дальнейшее сокращение времени, мне кажется, делает эффект очень резким.

2022-04-19 19:38 UTC, closed without merging